import React from 'react';
import { LazySkeletonEngine, SkeletonNode, SkeletonType, SkeletonOptions } from '../domain/SkeletonManager';

interface SkeletonLoaderProps {
  type?: SkeletonType;
  options?: SkeletonOptions;
  customClassName?: string;
}

/**
 * Recursive renderer for SkeletonNode structure generated by OOP Skeleton Engine
 */
const RenderNode: React.FC<{ node: SkeletonNode }> = ({ node }) => {
  const children = node.children?.map((child) => (
    <RenderNode key={child.id} node={child} />
  ));

  const baseStyle = `${node.className || ''} ${node.width || ''} ${node.height || ''}`;

  switch (node.type) {
    case 'grid':
    case 'card':
    case 'box':
    case 'table-row':
      return <div className={baseStyle}>{children}</div>;
    case 'text':
      return <div className={`animate-pulse ${baseStyle}`} />;
    case 'circle':
      return <div className={`animate-pulse rounded-full ${baseStyle}`} />;
    default:
      return <div className={baseStyle}>{children}</div>;
  }
};

export const SkeletonLoader: React.FC<SkeletonLoaderProps> = ({
  type = 'dashboard',
  options = {},
  customClassName = '',
}) => {
  const engine = LazySkeletonEngine.getInstance();
  const schema = engine.getSkeletonSchema(type, options);

  return (
    <div className={`${schema.containerClassName} ${customClassName}`}>
      {schema.nodes.map((node) => (
        <RenderNode key={node.id} node={node} />
      ))}
    </div>
  );
};
